/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4.2/userguide/building_java_projects.html
 */

plugins {
    kotlin("multiplatform") version "1.9.0"
    id("com.ncorti.ktfmt.gradle") version "0.13.0"
}

java {
   toolchain.languageVersion.set(JavaLanguageVersion.of(18))
}

repositories {
    mavenCentral()
}

kotlin {
    targets {
        jvm()
        linuxX64()
        macosArm64() {
            binaries {
            executable {
                entryPoint = "com.umaumax.waits.main"
                runTask?.args("")
            }
        }
        }
    }
    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.2")
                implementation("org.jetbrains.kotlinx:kotlinx-cli:0.3.5")
                implementation("com.michael-bull.kotlin-result:kotlin-result:1.1.18")
                implementation("com.michael-bull.kotlin-result:kotlin-result-coroutines:1.1.18")
            }
        }
        val commonTest by getting {
            dependsOn(commonMain)
            dependencies {
                implementation("org.jetbrains.kotlin:kotlin-test")
                implementation("org.jetbrains.kotlin:kotlin-test-junit")
            }
        }
        val jvmMain by getting {
            dependsOn(commonMain)
        }
    }
}

tasks.withType<Jar> {
    doFirst {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        val main by kotlin.jvm().compilations.getting
        manifest {
            attributes(
                "Main-Class" to "com.umaumax.waits.AppKt",
            )
        }
        from({
            main.runtimeDependencyFiles.files.filter { it.name.endsWith("jar") }.map { zipTree(it) }
        })
    }
}
